apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: autonomousdatabase-sample
spec:
  details:
    compartmentOCID: ocid1.tenancy.oc1..aaaaaaaabls4dzottlktt774tu3knax6crpozycjhrqpm73thfryxwlkmkba
    dbName: OsagaCoordPDB
    displayName: OsagaCoordPDB
    dbVersion: 21c
    cpuCoreCount: 1
    adminPassword:
      k8sSecretName: admin-password
    dataStorageSizeInTBs: 1
  ociConfig:
    configMapName: oci-cred
    secretName: oci-privatekey
