apiVersion: clusters.verrazzano.io/v1alpha1
kind: VerrazzanoProject
metadata:
  name: msdataworkshop
  namespace: msdataworkshop
spec:
  template:
    namespaces:
      - metadata:
          name: msdataworkshop
  placement:
    clusters:
      - name: %CLUSTERS_NAME%
