apiVersion: v1
kind: Service
metadata:
  name: db-metrics-exporter-order
  labels:
    app: db-metrics-exporter-order
    release: stable
spec:
  type: LoadBalancer
  ports:
    - port: 9161
      name: metrics
  selector:
    app: db-metrics-exporter-order
