## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertlog-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertlog
  template:
    metadata:
      labels:
        app: alertlog
        version: helidon-mp
    spec:
      containers:
      - name: alertlog
        image: %DOCKER_REGISTRY%/alertlog-exporter:0.1
        imagePullPolicy: Always
        env:
        - name: oracle.ucp.jdbc.PoolDataSource.alertlogpdb.user
          value: "%USER%"
        - name: oracle.ucp.jdbc.PoolDataSource.alertlogpdb.URL
          value: "jdbc:oracle:thin:@%PDB_NAME%_tp?TNS_ADMIN=/msdataworkshop/creds"
        - name: oracle.ucp.jdbc.PoolDataSource.alertlogpdb.password
          valueFrom:
            secretKeyRef:
              name: dbuser
              key: dbpassword
              optional: true
#       The following QUERY_SQL can be any query but must contain EXECUTION_CONTEXT_ID
        - name: QUERY_SQL
          value: "select ORIGINATING_TIMESTAMP, MODULE_ID, EXECUTION_CONTEXT_ID, MESSAGE_TEXT from V$diag_alert_ext"
        - name: OCI_REGION
          value: "%OCI_REGION%"
        - name: VAULT_SECRET_OCID
          value: "%VAULT_SECRET_OCID%"
        volumeMounts:
        - name: creds
          mountPath: /msdataworkshop/creds
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet: #alternatives include exec with command, etc.
            path: /health/live
            port: 8080
          initialDelaySeconds: 220
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 3
      restartPolicy: Always
      volumes:
      - name: creds
        secret:
          secretName: db-wallet-secret