apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-frontend
  labels:
    release: stable
spec:
  endpoints:
    - interval: 30s
      port: metrics
#      basicAuth:
#        password:
#          name: basic-auth
#          key: password
#        username:
#          name: basic-auth
#          key: user
  selector:
    matchLabels:
      app: frontend
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-order
  labels:
    release: stable
spec:
  endpoints:
    - interval: 3s
      port: metrics
  selector:
    matchLabels:
      app: order
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-inventory
  labels:
    release: stable
spec:
  endpoints:
    - interval: 30s
      port: metrics
  selector:
    matchLabels:
      app: inventory
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-db-teq-exporter-order
  labels:
    app: db-teq-exporter-order
    release: stable
spec:
  endpoints:
    - interval: 30s
      port: metrics
  selector:
    matchLabels:
      app: db-teq-exporter-order
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-db-teq-exporter-inventory
  labels:
    app: db-teq-exporter-inventory
    release: stable
spec:
  endpoints:
    - interval: 30s
      port: metrics
  selector:
    matchLabels:
      app: db-teq-exporter-inventory
