apiVersion: v1
items:
  - apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    metadata:
      annotations:
        meta.helm.sh/release-name: stable
        meta.helm.sh/release-namespace: default
      creationTimestamp: "2021-06-28T18:34:51Z"
      generation: 1
      labels:
        app: kube-prometheus-stack-prometheus
        app.kubernetes.io/instance: stable
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 16.12.0
        chart: kube-prometheus-stack-16.12.0
        heritage: Helm
        release: stable
      managedFields:
        - apiVersion: monitoring.coreos.com/v1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:annotations:
                .: {}
                f:meta.helm.sh/release-name: {}
                f:meta.helm.sh/release-namespace: {}
              f:labels:
                .: {}
                f:app: {}
                f:app.kubernetes.io/instance: {}
                f:app.kubernetes.io/managed-by: {}
                f:app.kubernetes.io/part-of: {}
                f:app.kubernetes.io/version: {}
                f:chart: {}
                f:heritage: {}
                f:release: {}
            f:spec:
              .: {}
              f:alerting:
                .: {}
                f:alertmanagers: {}
              f:enableAdminAPI: {}
              f:externalUrl: {}
              f:image: {}
              f:listenLocal: {}
              f:logFormat: {}
              f:logLevel: {}
              f:paused: {}
              f:podMonitorNamespaceSelector: {}
              f:podMonitorSelector:
                .: {}
                f:matchLabels:
                  .: {}
                  f:release: {}
              f:portName: {}
              f:probeNamespaceSelector: {}
              f:probeSelector:
                .: {}
                f:matchLabels:
                  .: {}
                  f:release: {}
              f:replicas: {}
              f:retention: {}
              f:routePrefix: {}
              f:ruleNamespaceSelector: {}
              f:ruleSelector:
                .: {}
                f:matchLabels:
                  .: {}
                  f:app: {}
                  f:release: {}
              f:securityContext:
                .: {}
                f:fsGroup: {}
                f:runAsGroup: {}
                f:runAsNonRoot: {}
                f:runAsUser: {}
              f:serviceAccountName: {}
              f:serviceMonitorNamespaceSelector: {}
              f:serviceMonitorSelector:
                .: {}
                f:matchLabels:
                  .: {}
                  f:release: {}
              f:shards: {}
              f:version: {}
          manager: Go-http-client
          operation: Update
          time: "2021-06-28T18:34:51Z"
      name: stable-kube-prometheus-sta-prometheus
      namespace: default
      resourceVersion: "1458926"
      selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/prometheuses/stable-kube-prometheus-sta-prometheus
      uid: 039089b6-d568-41e2-b525-d84d23e220f9
    spec:
      alerting:
        alertmanagers:
          - apiVersion: v2
            name: stable-kube-prometheus-sta-alertmanager
            namespace: default
            pathPrefix: /
            port: web
      enableAdminAPI: false
      externalUrl: http://stable-kube-prometheus-sta-prometheus.default:9090
      image: quay.io/prometheus/prometheus:v2.27.1
      listenLocal: false
      logFormat: logfmt
      logLevel: info
      paused: false
      podMonitorNamespaceSelector: {}
      podMonitorSelector:
        matchLabels:
          release: stable
      portName: web
      probeNamespaceSelector: {}
      probeSelector:
        matchLabels:
          release: stable
      replicas: 1
      retention: 10d
      routePrefix: /
      ruleNamespaceSelector: {}
      ruleSelector:
        matchLabels:
          app: kube-prometheus-stack
          release: stable
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: stable-kube-prometheus-sta-prometheus
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelector:
        matchLabels:
          release: stable
      shards: 1
      version: v2.27.1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""