apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-frontend
  labels:
    release: stable
spec:
  endpoints:
    - interval: 5s
      port: https
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      basicAuth:
        password:
          name: frontendadmin
          key: password
        username:
          name: frontendadmin
          key: user
  selector:
    matchLabels:
      app: frontend
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-order
  labels:
    release: stable
spec:
  endpoints:
    - interval: 5s
      port: metrics
  selector:
    matchLabels:
      app: order
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-inventory
  labels:
    release: stable
spec:
  endpoints:
    - interval: 5s
      port: metrics
  selector:
    matchLabels:
      app: inventory
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-db-metrics-exporter-order
  labels:
    app: db-metrics-exporter-order
    release: stable
spec:
  endpoints:
    - interval: 20s
      port: metrics
  selector:
    matchLabels:
      app: db-metrics-exporter-order
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-db-metrics-exporter-inventory
  labels:
    app: db-metrics-exporter-inventory
    release: stable
spec:
  endpoints:
    - interval: 20s
      port: metrics
  selector:
    matchLabels:
      app: db-metrics-exporter-inventory
